version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-evo
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_ENCRYPTION_KEY=evo-ai-n8n-encryption-key-2024
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      - whatsapp-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  whatsapp-network:
    driver: bridge

volumes:
  n8n-data: 