version: "3.8"

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=evo_whatsapp_integration_2024
      - DATABASE_ENABLED=false
      - WEBSOCKET_ENABLED=true
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://host.docker.internal:8000/whatsapp/webhook
      - WEBHOOK_EVENTS=messages,status
    volumes:
      - ./evolution-instances:/evolution/instances
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - evolution-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manager/instance/findAll || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  evolution-network:
    driver: bridge
